PENDING = "PENDING"
REJECTED = "REJECTED"
APPROVED = "APPROVED"
REIMBURSED = "REIMBURSED"


APPROVAL_STATUS = (
    (PENDING, "Pending"),
    (REJECTED, "Rejected"),
    (APPROVED, "Approved"),
    (REIMBURSED, "Reimbursed"),
)
