# Generated by Django 5.0.2 on 2024-02-16 15:34

import django.core.validators
import expense.models
import expense.validators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("expense_title", models.CharField(max_length=60)),
                (
                    "expense_description",
                    models.CharField(blank=True, max_length=300),
                ),
                (
                    "receipt",
                    models.FileField(
                        upload_to=expense.models.get_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "xlsx",
                                    "xls",
                                ]
                            ),
                            functools.partial(
                                expense.validators.validate_max_file_size,
                                *(),
                                **{"max_size": 5242880}
                            ),
                        ],
                    ),
                ),
                (
                    "approval_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("REJECTED", "Rejected"),
                            ("APPROVED", "Approved"),
                            ("REIMBURSED", "Reimbursed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
            },
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "approval_status__in",
                        ["PENDING", "REJECTED", "APPROVED", "REIMBURSED"],
                    )
                ),
                name="valid_status_constraint",
            ),
        ),
    ]
